import java.awt.*;
import javax.swing.*;
import java.io.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;

/**
 *
 * @author NCRK (नवीन चौहान राजपूत खरदौनी)
 */
public class JFrame1 extends javax.swing.JFrame implements KeyListener
{
private Property pro ;

    public JFrame1(Property pro) 
    {
        this.path = new  java.util.Vector<>();
        this.filename = new java.util.Vector<>();
        this.textArea = new java.util.Vector<>();
        this.scrollPane = new java.util.Vector<>();
        this.countTab = new java.util.Vector<>();
        this.countSpace = new java.util.Vector<>();
        this.pro = pro;
        initComponents();
        this.setBounds(this.pro.getRect());
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("Images/all.gif"));
        setTitle("NCRK :: TextEditor v4.0");
        if(this.pro.getFont_style()==1) 
        {
            jToggleButton1.setSelected(true);
        }
        else if(this.pro.getFont_style()==2)
        {
            jToggleButton2.setSelected(true);
        }
       jTabbedPane2.setTabPlacement(JTabbedPane.TOP);
       {
        ++i;
        ++ni;
         _new();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem18 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        jMenuItem18.setText("null");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.gif"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.gif"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circle-x-2x.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-in-2x.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-out-2x.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.gif"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cut.gif"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/copy.gif"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paste.gif"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/undo.gif"))); // NOI18N
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/redo.gif"))); // NOI18N
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.gif"))); // NOI18N
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton13);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bold.gif"))); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/italic.gif"))); // NOI18N
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench-2x.png"))); // NOI18N
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/question.gif"))); // NOI18N
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        jScrollPane1.setViewportView(jToolBar1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.gif"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jMenuItem1.setText(bundle.getString("NEW")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Save As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText(bundle.getString("SAVE ALL")); // NOI18N
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText(bundle.getString("CLOSE")); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText(bundle.getString("CLOSE ALL")); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText(bundle.getString("PRINT")); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator4);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText(bundle.getString("EXIT")); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("EDIT")); // NOI18N

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Undo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Redo");
        jMenu2.add(jMenuItem11);
        jMenu2.add(jSeparator5);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Cut");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("Copy");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Paste");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);
        jMenu2.add(jSeparator6);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Select All");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenuItem15.setText("Text Color");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem26.setText("Background Color");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem26);

        jMenuItem27.setText("Font");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem27);

        jMenu11.setText("Look and Feel");

        jMenuItem31.setText("Nimbus");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem31);

        jMenu13.setText("Metal");

        jMenuItem34.setText("Default(Steel)");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem34);

        jMenuItem36.setText("Ocean");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem36);

        jMenu11.add(jMenu13);

        jMenuItem42.setText("Nimbus1");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem42);

        jMenuItem33.setText("Windows");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem33);

        jMenuItem32.setText("Windows Classics");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem32);

        jMenuItem30.setText("CDE/Motif");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem30);

        jMenuItem37.setText("GTK");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem37);

        jMenuItem39.setText("Basic");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem39);

        jMenuItem40.setText("Synth");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem40);

        jMenuItem41.setText("Multiplexing");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem41);

        jMenuItem38.setText("System");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem38);

        jMenu3.add(jMenu11);

        jMenu9.setText("ZOOM");

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_EQUALS, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setText("Zoom IN");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem17);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem19.setText("Zoom OUT");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenu3.add(jMenu9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Search");

        jMenuItem20.setText("Find Previous");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setText("Find");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem21);

        jMenuItem22.setText("Find Next");
        jMenu4.add(jMenuItem22);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem23.setText("Replace");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Setting");

        jMenuItem35.setText("Reset to Default");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem35);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("About Us");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
         setI(getI() + 1);
        setNi(getNi() + 1);
        if(getI()<getMaxTab()) _new();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        setI(getI() + 1);
       if(getI()<getMaxTab()) {
           _open(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
         int si =getjTabbedPane2().getSelectedIndex();
         if(si==-1) {
             return;
         }
        _save(si);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
        _close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,"Are you sure to exit ?", "Exit", 1,QUESTION_MESSAGE);
        if(choice==0) System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
         
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
         
        _zoomIn();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
         
        _zoomOut();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
         
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         
        setI(getI() + 1);
       if(getjTabbedPane2().getTabCount()<getMaxTab()) {
           _open(true);
      }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         
        setI(getI() + 1);
        setNi(getNi() + 1);
        if(getjTabbedPane2().getTabCount()<getMaxTab()) {
            _new();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         
        int si =getjTabbedPane2().getSelectedIndex();
        if(si==-1) return;
        _save(si);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         
        int si =getjTabbedPane2().getSelectedIndex();
        if(si==-1) return;
        _saveAs(si);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         
        _close();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
         
        _paste();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
         
        _cut();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
         
        _copy();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
         
       javax.swing.JTextPane jp = new JTextPane();
       jp.setEnabled(true);
       jp.setVisible(true);
       jp.add(new JLabel("Close"));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        _zoomIn();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
        _zoomOut();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        boolean bold = getjToggleButton1().isSelected();
        boolean italic = getjToggleButton2().isSelected();
        if(!bold && !italic)
        {
            getPro().setFont_style(0); 
        }
        else if(bold && !italic)
        {
            getPro().setFont_style(1);
        }
        else
        {
            getjToggleButton2().setSelected(false);
            getPro().setFont_style(1);
        }
        for(int temp =0;temp<getI();temp++) {
            textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        boolean bold = getjToggleButton1().isSelected();
        boolean italic = getjToggleButton2().isSelected();
        if(!bold && !italic)
        {
       
            getPro().setFont_style(0); 
        }
        else if(!bold && italic)
        {
            getPro().setFont_style(2);
        }
        else
        {
            getjToggleButton1().setSelected(false);
            getPro().setFont_style(2);
        }
        for(int temp =0;temp<getI();temp++) {
            textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         
        _cut();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         
        _copy();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         
        _paste();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    PrintJob p = Toolkit.getDefaultToolkit().getPrintJob(this, getjTabbedPane2().getTitleAt(getjTabbedPane2().getSelectedIndex()), null, null);
        
       Graphics g1 =p.getGraphics();
       g1.dispose();
       p.end();
      
       
       
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
         
        _selectAll();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
         
        _foregroundColorChooser();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
         
        _backgroundColorChooser();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
         
        JDialog aboutus = new JDialog(this,"About us",true);
        aboutus.setBounds(200,100,300,250);
        JLabel l = new JLabel("ॐ नम: शिवाय !");
        aboutus.add(l);
        aboutus.setVisible(true);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
         
        _aboutus();
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       javax.swing.JTextPane jp = new JTextPane();
       jp.setEnabled(true);
       jp.setVisible(true);
       jp.add(new JLabel("Close"));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    _aboutus();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        m32_Click(evt);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this,"Are you sure to exit ?", "Exit", 1,QUESTION_MESSAGE);
        if(choice==0) 
        {
            pro.setRect(this.getBounds());
            getPro().writeProperties();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        _closeAll();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.put("nimbusBase", new Color(255,100,100));
               UIManager.put("control", new Color(255,0,100));
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Nimbus");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Windows");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Windows Classic");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("CDE/Motif");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        Search search = new Search(this,1);
        search.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        Search search = new Search(this,0);
        search.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
         int option = JOptionPane.showConfirmDialog(this, "Are you sure to reset?\nNote::Save opened file before confirming to reset.");
         if(option==0)
         {
             String[] arg = new String[2];
             arg[0] = "readme.txt";
             this.dispose();
             main(arg);
             
         }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        try {
            javax.swing.plaf.metal.MetalTheme theme=new javax.swing.plaf.metal.OceanTheme();
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(theme);
            try {
                UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
            getPro().setLook("OceanTheme");
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
       try {
           
           try {
               javax.swing.plaf.metal.MetalTheme theme=new javax.swing.plaf.metal.DefaultMetalTheme();
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(theme);
               UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
         try {
           
           try {
              
               UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        
              try {
           
           try {
              
               UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
      
              try {
           
           try {
              
               UIManager.setLookAndFeel("javax.swing.plaf.basic.BasicLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
           try {
           
           try {
              
               UIManager.setLookAndFeel("javax.swing.plaf.synth.SynthLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
} 
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        try {
          
           try {
              
               UIManager.setLookAndFeel("javax.swing.plaf.multi.MultiLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
} 
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
           try {
          
           try {
              
               UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
           }
    
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE, null, ex);
}    
    }//GEN-LAST:event_jMenuItem42ActionPerformed
void _new()
{
        this.textArea.add(getI(), new JTextArea("")) ;
        this.scrollPane.add(getI(), new JScrollPane());
        this.scrollPane.get(getI()).setViewportView(this.textArea.get(getI()));
        this.textArea.get(getI()).setTabSize(4);
        this.textArea.get(getI()).grabFocus();
        this.getjTabbedPane2().addTab("New "+getNi(),this.scrollPane.get(getI()));
        this.textArea.get(getI()).setFont(new Font(getPro().getFont_name(), this.getPro().getFont_style(), getPro().getFont_size()));
        this.textArea.get(getI()).setBackground(getPro().getBgcolor());
        this.textArea.get(getI()).setForeground(getPro().getFgcolor());
        this.textArea.get(getI()).select(0, 0);
        this.textArea.get(getI()).addKeyListener(this);
        this.path.add("");
        this.filename.add("");
}
    
void _open(boolean _new)
	{
		//_close();
        if(_new)
        {
	setO(new FileDialog(this,"Open Files"));
        getO().setVisible(true);
        }
        if(getO().getFile()!=null||!_new)
        {
            if(_new)
            {
                path.add(getI(),getO().getDirectory()+getO().getFile());
                filename.add(getI(),getO().getFile());
            }
            byte[] b;
            try 
            ( //for byte oriented i/o
                    FileInputStream fin = new FileInputStream(path.get(getI()))) 
            {
                    int n = fin.available();
                    b = new byte[n];
                    fin.read(b,0,n); 
                String str = new String(b);
                
                this.textArea.add(getI(), new JTextArea(""));
                this.textArea.get(getI()).setTabSize(2); this.textArea.get(getI()).grabFocus();
                this.textArea.get(getI()).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
                this.textArea.get(getI()).setBackground(getPro().getBgcolor());
                this.textArea.get(getI()).setForeground(getPro().getFgcolor());
                this.textArea.get(getI()).setText(str);
                this.textArea.get(getI()).setTabSize(4);
                this.scrollPane.add(getI(), new JScrollPane());
                this.scrollPane.get(getI()).setViewportView( this.textArea.get(getI()));
                this.getjTabbedPane2().addTab(getO().getFile(), this.scrollPane.get(getI()));
                this.scrollPane.get(getI()).setEnabled(true);
                this.scrollPane.get(getI()).setWheelScrollingEnabled(true);
            }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to read the file\n "+path.get(getI())+e,"Error",0);
                this.textArea.get(getI()).setText("");
        }
        }
        else {
            setI(getI() - 1);
            }
	}

void _save(int i)
{
	if(path.get(i).equals(""))
        {
            setO(new FileDialog(this,"Save",1));
            getO().setVisible(true);   
        if( getO().getFile()!=null)
        {
                filename.setElementAt(getO().getFile(), i);
                path.setElementAt(getO().getDirectory()+filename.get(i), i);
        }
        else
        {
            return;
        }
	}    
        try (FileOutputStream fout = new FileOutputStream(path.get(i))) {
                String txt =  textArea.get(i).getText();
                byte[] b = txt.getBytes();
                fout.write(b,0,b.length);
            
            getjTabbedPane2().setTitleAt(i, filename.get(i));
        
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to save the content into the file\n "+path.get(i)+e,"Error",0);
        }
        
        
}
        
    void _saveAs(int i)
{
    
	setO(new FileDialog(this,"Save As",1));
        getO().setVisible(true);
        if(getO().getFile()!=null)
        {
            filename.setElementAt(getO().getFile(), i);
            path.setElementAt(getO().getDirectory()+filename.get(i), i);
            try (FileOutputStream fout = new FileOutputStream(path.get(i))) {
            String txt = textArea.get(i).getText();
            byte[] b = txt.getBytes();
            fout.write(b,0,b.length);
            getjTabbedPane2().setTitleAt(i,filename.get(i));
        }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to save the content into the file\n "+path.get(i)+e,"Error",0);
        }
        }
               
}
    void _saveAll()
    {
        for(int temp = 0;temp<=getI();temp++)
        {
            this._save(temp);
        }
    }

    void _close()
	{
            int si = getjTabbedPane2().getSelectedIndex();
            if(si==-1) {
                return;
            }
            this.setI(this.getI()-1);
            this.textArea.remove(si);
            this.scrollPane.remove(si);
            path.remove(si);
            filename.remove(si);
            getjTabbedPane2().remove(si);
	}
   
     void _closeAll()
    {
        int choice = JOptionPane.showConfirmDialog(this,"Do you want to save the changes before exiting exiting?");
	if(choice == 0)
        {
                            
        }
    }
    void _cut()
    {
         int si =getjTabbedPane2().getSelectedIndex();
         textArea.get(si).cut();
    }
    void _copy()
    {
         int si =getjTabbedPane2().getSelectedIndex();
         textArea.get(si).copy();
    }
    void _paste()
    {
        int si =getjTabbedPane2().getSelectedIndex();
        textArea.get(si).paste();
    }
    void _selectAll()
    {
        int si =getjTabbedPane2().getSelectedIndex();
        textArea.get(si).selectAll();
    }
void _zoomIn()
{
	if(getPro().getFont_size()<72)
	{
            getPro().setFont_size(getPro().getFont_size() + 1);
            for(int temp=0;temp<=getI();temp++) {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
}
void _zoomOut()
{
	if(getPro().getFont_size()>12)
	{
            getPro().setFont_size(getPro().getFont_size() - 1);
            for(int temp=0;temp<=getI();temp++) {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
	}
        
}

void _foregroundColorChooser()
{
    new ForegroundColorChooser(this, this).setVisible(true);
}



void _backgroundColorChooser()
{
   new BackgroundColorChooser(this, this).setVisible(true);
}
void _aboutus()
{
    AboutUs aboutus = new AboutUs(this);
    
}

void _setFontStyle()
{
    boolean state = getjToggleButton2().isSelected();
        if(state)
        {
            for(int temp = 0;temp<=getI();temp++)
            {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
        else
        {
            for(int temp = 0;temp<=getI();temp++)
            {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
}


       void m32_Click(ActionEvent e)
{
	//Font
	FontDialog f=new FontDialog( this);
	f.setVisible(true);
}
       
       
       /*
        Key Event handler Functions
       
       */
       public  void keyPressed(KeyEvent ke)
       {
           
       }
       public  void keyTyped(KeyEvent ke)
       {
           int keyCode = ke.getKeyCode();
           boolean space = false;
           boolean tab = false;
           if(keyCode == KeyEvent.VK_TAB) tab = true;
           else if(keyCode == KeyEvent.VK_SPACE) space = true;
           else return;
           int si = jTabbedPane2.getSelectedIndex();
           if(space)
           {
               this.countSpace.set(si, this.countSpace.get(si)+1);
           }
           else
           {
               this.countTab.set(si, this.countTab.get(si));
           }
           
       }
       public  void keyReleased(KeyEvent ke)
       {
           
       }
void db_click_open(String [] args)
{
   int j = 0;
    while(j<args.length)
    {
            setI(getI() + 1);
            textArea.add(getI(), new JTextArea(""));
            textArea.get(getI()).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
	    path.setElementAt( args[j],getI());
            byte[] b;
            try ( //for byte oriented i/o
                FileInputStream fin = new FileInputStream((String)path.get(getI()))) {
                int n = fin.available();
                b = new byte[n];
                fin.read(b,0,n);  
                String str = new String(b);
                textArea.get(getI()).setText(str);
                textArea.get(getI()).setTabSize(2);
            
                scrollPane.add(getI(), new JScrollPane());
                scrollPane.get(getI()).setViewportView(textArea.get(getI()));
                getjTabbedPane2().addTab(getO().getFile(), scrollPane.get(getI()));
                scrollPane.get(getI()).setEnabled(true);
                scrollPane.get(getI()).setWheelScrollingEnabled(rootPaneCheckingEnabled);
        }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to read the file\n "+path.get(getI())+e,"Error",0);
                textArea.get(getI()).setText("");
                setI(getI() - 1);
        }
        
        //else i--;
    }
   
}

public javax.swing.JTabbedPane getjTabbedPane2()
    {
        return this.jTabbedPane2;
    }
 
    public static void main(String args[]) {
        Property pro = null;
        if(args.length==0)
        {
             pro = Property.getProperty(true);
        }
        else
        {
             pro = Property.getProperty(false);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (pro.getLook().equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>

        /* Create and display the form */
        Starting s = new Starting();
        s.setVisible(true);
        
        try
        {
            Thread.sleep(1000);
            
        }
        catch(InterruptedException e)
        {
            
        }
        s.dispose();
         JFrame1 f =  new JFrame1(pro);
                 f.setVisible(true);
//           System.out.println(args[0]);
          
          
         
        try
        {
        f.db_click_open(args);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }

private int MaxTab = 200;
private FileDialog o;
java.util.Vector<String> path;
java.util.Vector<String> filename;
java.util.Vector<Integer> countTab;
java.util.Vector<Integer> countSpace;
private int i=-1;
private int ni;//for indexing of New Tab (un-Saved)
java.util.Vector<JTextArea> textArea ;
java.util.Vector<JScrollPane> scrollPane ;
private String copiedText = "";
private GraphicsEnvironment g;
//private char[] ch;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pro
     */
    public Property getPro() {
        return pro;
    }

    /**
     * @param pro the pro to set
     */
    public void setPro(Property pro) {
        this.pro = pro;
    }

    /**
     * @return the MaxTab
     */
    public int getMaxTab() {
        return MaxTab;
    }

    /**
     * @param MaxTab the MaxTab to set
     */
    public void setMaxTab(int MaxTab) {
        this.MaxTab = MaxTab;
    }

    /**
     * @return the o
     */
    public FileDialog getO() {
        return o;
    }

    /**
     * @param o the o to set
     */
    public void setO(FileDialog o) {
        this.o = o;
    }

    /**
     * @return the i
     */
    public int getI() {
        return i;
    }

    /**
     * @param i the i to set
     */
    public void setI(int i) {
        this.i = i;
    }

    /**
     * @return the ni
     */
    public int getNi() {
        return ni;
    }

    /**
     * @param ni the ni to set
     */
    public void setNi(int ni) {
        this.ni = ni;
    }

    /**
     * @return the copiedText
     */
    public String getCopiedText() {
        return copiedText;
    }

    /**
     * @param copiedText the copiedText to set
     */
    public void setCopiedText(String copiedText) {
        this.copiedText = copiedText;
    }

    /**
     * @return the g
     */
    public GraphicsEnvironment getG() {
        return g;
    }

    /**
     * @param g the g to set
     */
    public void setG(GraphicsEnvironment g) {
        this.g = g;
    }


    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton10
     */
    public javax.swing.JButton getjButton10() {
        return jButton10;
    }

    /**
     * @param jButton10 the jButton10 to set
     */
    public void setjButton10(javax.swing.JButton jButton10) {
        this.jButton10 = jButton10;
    }

    /**
     * @return the jButton11
     */
    public javax.swing.JButton getjButton11() {
        return jButton11;
    }

    /**
     * @param jButton11 the jButton11 to set
     */
    public void setjButton11(javax.swing.JButton jButton11) {
        this.jButton11 = jButton11;
    }

    /**
     * @return the jButton12
     */
    public javax.swing.JButton getjButton12() {
        return jButton12;
    }

    /**
     * @param jButton12 the jButton12 to set
     */
    public void setjButton12(javax.swing.JButton jButton12) {
        this.jButton12 = jButton12;
    }

    /**
     * @return the jButton13
     */
    public javax.swing.JButton getjButton13() {
        return jButton13;
    }

    /**
     * @param jButton13 the jButton13 to set
     */
    public void setjButton13(javax.swing.JButton jButton13) {
        this.jButton13 = jButton13;
    }

    /**
     * @return the jButton14
     */
    public javax.swing.JButton getjButton14() {
        return jButton14;
    }

    /**
     * @param jButton14 the jButton14 to set
     */
    public void setjButton14(javax.swing.JButton jButton14) {
        this.jButton14 = jButton14;
    }

    /**
     * @return the jButton16
     */
    public javax.swing.JButton getjButton16() {
        return jButton16;
    }

    /**
     * @param jButton16 the jButton16 to set
     */
    public void setjButton16(javax.swing.JButton jButton16) {
        this.jButton16 = jButton16;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.jButton3 = jButton3;
    }

    /**
     * @return the jButton4
     */
    public javax.swing.JButton getjButton4() {
        return jButton4;
    }

    /**
     * @param jButton4 the jButton4 to set
     */
    public void setjButton4(javax.swing.JButton jButton4) {
        this.jButton4 = jButton4;
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    /**
     * @return the jButton6
     */
    public javax.swing.JButton getjButton6() {
        return jButton6;
    }

    /**
     * @param jButton6 the jButton6 to set
     */
    public void setjButton6(javax.swing.JButton jButton6) {
        this.jButton6 = jButton6;
    }

    /**
     * @return the jButton7
     */
    public javax.swing.JButton getjButton7() {
        return jButton7;
    }

    /**
     * @param jButton7 the jButton7 to set
     */
    public void setjButton7(javax.swing.JButton jButton7) {
        this.jButton7 = jButton7;
    }

    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return jButton8;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.jButton8 = jButton8;
    }

    /**
     * @return the jButton9
     */
    public javax.swing.JButton getjButton9() {
        return jButton9;
    }

    /**
     * @param jButton9 the jButton9 to set
     */
    public void setjButton9(javax.swing.JButton jButton9) {
        this.jButton9 = jButton9;
    }

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @param jMenu1 the jMenu1 to set
     */
    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }


    /**
     * @return the jMenu11
     */
    public javax.swing.JMenu getjMenu11() {
        return jMenu11;
    }

    /**
     * @param jMenu11 the jMenu11 to set
     */
    public void setjMenu11(javax.swing.JMenu jMenu11) {
        this.jMenu11 = jMenu11;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @param jMenu2 the jMenu2 to set
     */
    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     * @return the jMenu3
     */
    public javax.swing.JMenu getjMenu3() {
        return jMenu3;
    }

    /**
     * @param jMenu3 the jMenu3 to set
     */
    public void setjMenu3(javax.swing.JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    /**
     * @return the jMenu4
     */
    public javax.swing.JMenu getjMenu4() {
        return jMenu4;
    }

    /**
     * @param jMenu4 the jMenu4 to set
     */
    public void setjMenu4(javax.swing.JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    /**
     * @return the jMenu5
     */
    public javax.swing.JMenu getjMenu5() {
        return jMenu5;
    }

    /**
     * @param jMenu5 the jMenu5 to set
     */
    public void setjMenu5(javax.swing.JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    /**
     * @return the jMenu8
     */
    public javax.swing.JMenu getjMenu8() {
        return jMenu8;
    }

    /**
     * @param jMenu8 the jMenu8 to set
     */
    public void setjMenu8(javax.swing.JMenu jMenu8) {
        this.jMenu8 = jMenu8;
    }

    /**
     * @return the jMenu9
     */
    public javax.swing.JMenu getjMenu9() {
        return jMenu9;
    }

    /**
     * @param jMenu9 the jMenu9 to set
     */
    public void setjMenu9(javax.swing.JMenu jMenu9) {
        this.jMenu9 = jMenu9;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @param jMenuItem1 the jMenuItem1 to set
     */
    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    /**
     * @return the jMenuItem10
     */
    public javax.swing.JMenuItem getjMenuItem10() {
        return jMenuItem10;
    }

    /**
     * @param jMenuItem10 the jMenuItem10 to set
     */
    public void setjMenuItem10(javax.swing.JMenuItem jMenuItem10) {
        this.jMenuItem10 = jMenuItem10;
    }

    /**
     * @return the jMenuItem11
     */
    public javax.swing.JMenuItem getjMenuItem11() {
        return jMenuItem11;
    }

    /**
     * @param jMenuItem11 the jMenuItem11 to set
     */
    public void setjMenuItem11(javax.swing.JMenuItem jMenuItem11) {
        this.jMenuItem11 = jMenuItem11;
    }

    /**
     * @return the jMenuItem12
     */
    public javax.swing.JMenuItem getjMenuItem12() {
        return jMenuItem12;
    }

    /**
     * @param jMenuItem12 the jMenuItem12 to set
     */
    public void setjMenuItem12(javax.swing.JMenuItem jMenuItem12) {
        this.jMenuItem12 = jMenuItem12;
    }

    /**
     * @return the jMenuItem13
     */
    public javax.swing.JMenuItem getjMenuItem13() {
        return jMenuItem13;
    }

    /**
     * @param jMenuItem13 the jMenuItem13 to set
     */
    public void setjMenuItem13(javax.swing.JMenuItem jMenuItem13) {
        this.jMenuItem13 = jMenuItem13;
    }

    /**
     * @return the jMenuItem14
     */
    public javax.swing.JMenuItem getjMenuItem14() {
        return jMenuItem14;
    }

    /**
     * @param jMenuItem14 the jMenuItem14 to set
     */
    public void setjMenuItem14(javax.swing.JMenuItem jMenuItem14) {
        this.jMenuItem14 = jMenuItem14;
    }

    /**
     * @return the jMenuItem15
     */
    public javax.swing.JMenuItem getjMenuItem15() {
        return jMenuItem15;
    }

    /**
     * @param jMenuItem15 the jMenuItem15 to set
     */
    public void setjMenuItem15(javax.swing.JMenuItem jMenuItem15) {
        this.jMenuItem15 = jMenuItem15;
    }

    /**
     * @return the jMenuItem16
     */
    public javax.swing.JMenuItem getjMenuItem16() {
        return jMenuItem16;
    }

    /**
     * @param jMenuItem16 the jMenuItem16 to set
     */
    public void setjMenuItem16(javax.swing.JMenuItem jMenuItem16) {
        this.jMenuItem16 = jMenuItem16;
    }

    /**
     * @return the jMenuItem17
     */
    public javax.swing.JMenuItem getjMenuItem17() {
        return jMenuItem17;
    }

    /**
     * @param jMenuItem17 the jMenuItem17 to set
     */
    public void setjMenuItem17(javax.swing.JMenuItem jMenuItem17) {
        this.jMenuItem17 = jMenuItem17;
    }

    /**
     * @return the jMenuItem18
     */
    public javax.swing.JMenuItem getjMenuItem18() {
        return jMenuItem18;
    }

    /**
     * @param jMenuItem18 the jMenuItem18 to set
     */
    public void setjMenuItem18(javax.swing.JMenuItem jMenuItem18) {
        this.jMenuItem18 = jMenuItem18;
    }

    /**
     * @return the jMenuItem19
     */
    public javax.swing.JMenuItem getjMenuItem19() {
        return jMenuItem19;
    }

    /**
     * @param jMenuItem19 the jMenuItem19 to set
     */
    public void setjMenuItem19(javax.swing.JMenuItem jMenuItem19) {
        this.jMenuItem19 = jMenuItem19;
    }

    /**
     * @return the jMenuItem2
     */
    public javax.swing.JMenuItem getjMenuItem2() {
        return jMenuItem2;
    }

    /**
     * @param jMenuItem2 the jMenuItem2 to set
     */
    public void setjMenuItem2(javax.swing.JMenuItem jMenuItem2) {
        this.jMenuItem2 = jMenuItem2;
    }

    /**
     * @return the jMenuItem20
     */
    public javax.swing.JMenuItem getjMenuItem20() {
        return jMenuItem20;
    }

    /**
     * @param jMenuItem20 the jMenuItem20 to set
     */
    public void setjMenuItem20(javax.swing.JMenuItem jMenuItem20) {
        this.jMenuItem20 = jMenuItem20;
    }

    /**
     * @return the jMenuItem21
     */
    public javax.swing.JMenuItem getjMenuItem21() {
        return jMenuItem21;
    }

    /**
     * @param jMenuItem21 the jMenuItem21 to set
     */
    public void setjMenuItem21(javax.swing.JMenuItem jMenuItem21) {
        this.jMenuItem21 = jMenuItem21;
    }

    /**
     * @return the jMenuItem22
     */
    public javax.swing.JMenuItem getjMenuItem22() {
        return jMenuItem22;
    }

    /**
     * @param jMenuItem22 the jMenuItem22 to set
     */
    public void setjMenuItem22(javax.swing.JMenuItem jMenuItem22) {
        this.jMenuItem22 = jMenuItem22;
    }

    /**
     * @return the jMenuItem23
     */
    public javax.swing.JMenuItem getjMenuItem23() {
        return jMenuItem23;
    }

    /**
     * @return the jMenuItem26
     */
    public javax.swing.JMenuItem getjMenuItem26() {
        return jMenuItem26;
    }

    /**
     * @param jMenuItem26 the jMenuItem26 to set
     */
    public void setjMenuItem26(javax.swing.JMenuItem jMenuItem26) {
        this.jMenuItem26 = jMenuItem26;
    }

    /**
     * @return the jMenuItem27
     */
    public javax.swing.JMenuItem getjMenuItem27() {
        return jMenuItem27;
    }

    /**
     * @param jMenuItem27 the jMenuItem27 to set
     */
    public void setjMenuItem27(javax.swing.JMenuItem jMenuItem27) {
        this.jMenuItem27 = jMenuItem27;
    }
    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return jMenuItem3;
    }

    /**
     * @param jMenuItem3 the jMenuItem3 to set
     */
    public void setjMenuItem3(javax.swing.JMenuItem jMenuItem3) {
        this.jMenuItem3 = jMenuItem3;
    }

    /**
     * @return the jMenuItem30
     */
    public javax.swing.JMenuItem getjMenuItem30() {
        return jMenuItem30;
    }

    /**
     * @param jMenuItem30 the jMenuItem30 to set
     */
    public void setjMenuItem30(javax.swing.JMenuItem jMenuItem30) {
        this.jMenuItem30 = jMenuItem30;
    }

    /**
     * @return the jMenuItem31
     */
    public javax.swing.JMenuItem getjMenuItem31() {
        return jMenuItem31;
    }

    /**
     * @param jMenuItem31 the jMenuItem31 to set
     */
    public void setjMenuItem31(javax.swing.JMenuItem jMenuItem31) {
        this.jMenuItem31 = jMenuItem31;
    }

    /**
     * @return the jMenuItem32
     */
    public javax.swing.JMenuItem getjMenuItem32() {
        return jMenuItem32;
    }

    /**
     * @param jMenuItem32 the jMenuItem32 to set
     */
    public void setjMenuItem32(javax.swing.JMenuItem jMenuItem32) {
        this.jMenuItem32 = jMenuItem32;
    }

    /**
     * @return the jMenuItem33
     */
    public javax.swing.JMenuItem getjMenuItem33() {
        return jMenuItem33;
    }

    /**
     * @param jMenuItem33 the jMenuItem33 to set
     */
    public void setjMenuItem33(javax.swing.JMenuItem jMenuItem33) {
        this.jMenuItem33 = jMenuItem33;
    }

    /**
     * @return the jMenuItem34
     */


    /**
     * @return the jMenuItem35
     */
    public javax.swing.JMenuItem getjMenuItem35() {
        return jMenuItem35;
    }

    /**
     * @param jMenuItem35 the jMenuItem35 to set
     */
    public void setjMenuItem35(javax.swing.JMenuItem jMenuItem35) {
        this.jMenuItem35 = jMenuItem35;
    }

    /**
     * @return the jMenuItem4
     */
    public javax.swing.JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    /**
     * @param jMenuItem4 the jMenuItem4 to set
     */
    public void setjMenuItem4(javax.swing.JMenuItem jMenuItem4) {
        this.jMenuItem4 = jMenuItem4;
    }

    /**
     * @return the jMenuItem5
     */
    public javax.swing.JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    /**
     * @param jMenuItem5 the jMenuItem5 to set
     */
    public void setjMenuItem5(javax.swing.JMenuItem jMenuItem5) {
        this.jMenuItem5 = jMenuItem5;
    }

    /**
     * @return the jMenuItem6
     */
    public javax.swing.JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    /**
     * @param jMenuItem6 the jMenuItem6 to set
     */
    public void setjMenuItem6(javax.swing.JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    /**
     * @return the jMenuItem7
     */
    public javax.swing.JMenuItem getjMenuItem7() {
        return jMenuItem7;
    }

    /**
     * @param jMenuItem7 the jMenuItem7 to set
     */
    public void setjMenuItem7(javax.swing.JMenuItem jMenuItem7) {
        this.jMenuItem7 = jMenuItem7;
    }

    /**
     * @return the jMenuItem8
     */
    public javax.swing.JMenuItem getjMenuItem8() {
        return jMenuItem8;
    }

    /**
     * @param jMenuItem8 the jMenuItem8 to set
     */
    public void setjMenuItem8(javax.swing.JMenuItem jMenuItem8) {
        this.jMenuItem8 = jMenuItem8;
    }

    /**
     * @return the jMenuItem9
     */
    public javax.swing.JMenuItem getjMenuItem9() {
        return jMenuItem9;
    }

    /**
     * @param jMenuItem9 the jMenuItem9 to set
     */
    public void setjMenuItem9(javax.swing.JMenuItem jMenuItem9) {
        this.jMenuItem9 = jMenuItem9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jSeparator1
     */
    public javax.swing.JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    /**
     * @param jSeparator1 the jSeparator1 to set
     */
    public void setjSeparator1(javax.swing.JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    /**
     * @return the jSeparator2
     */
    public javax.swing.JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    /**
     * @param jSeparator2 the jSeparator2 to set
     */
    public void setjSeparator2(javax.swing.JPopupMenu.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    /**
     * @return the jSeparator3
     */
    public javax.swing.JPopupMenu.Separator getjSeparator3() {
        return jSeparator3;
    }

    /**
     * @param jSeparator3 the jSeparator3 to set
     */
    public void setjSeparator3(javax.swing.JPopupMenu.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    /**
     * @return the jSeparator4
     */
    public javax.swing.JPopupMenu.Separator getjSeparator4() {
        return jSeparator4;
    }

    /**
     * @param jSeparator4 the jSeparator4 to set
     */
    public void setjSeparator4(javax.swing.JPopupMenu.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    /**
     * @return the jSeparator5
     */
    public javax.swing.JPopupMenu.Separator getjSeparator5() {
        return jSeparator5;
    }

    /**
     * @param jSeparator5 the jSeparator5 to set
     */
    public void setjSeparator5(javax.swing.JPopupMenu.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    /**
     * @return the jSeparator6
     */
    public javax.swing.JPopupMenu.Separator getjSeparator6() {
        return jSeparator6;
    }

    /**
     * @param jSeparator6 the jSeparator6 to set
     */
    public void setjSeparator6(javax.swing.JPopupMenu.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    /**
     * @param jTabbedPane2 the jTabbedPane2 to set
     */
    public void setjTabbedPane2(javax.swing.JTabbedPane jTabbedPane2) {
        this.jTabbedPane2 = jTabbedPane2;
    }

    /**
     * @return the jToggleButton1
     */
    public javax.swing.JToggleButton getjToggleButton1() {
        return jToggleButton1;
    }

    /**
     * @param jToggleButton1 the jToggleButton1 to set
     */
    public void setjToggleButton1(javax.swing.JToggleButton jToggleButton1) {
        this.jToggleButton1 = jToggleButton1;
    }

    /**
     * @return the jToggleButton2
     */
    public javax.swing.JToggleButton getjToggleButton2() {
        return jToggleButton2;
    }

    /**
     * @param jToggleButton2 the jToggleButton2 to set
     */
    public void setjToggleButton2(javax.swing.JToggleButton jToggleButton2) {
        this.jToggleButton2 = jToggleButton2;
    }

    /**
     * @return the jToolBar1
     */
    public javax.swing.JToolBar getjToolBar1() {
        return jToolBar1;
    }

    /**
     * @param jToolBar1 the jToolBar1 to set
     */
    public void setjToolBar1(javax.swing.JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }
}
