import java.awt.*;
import javax.swing.*;
import java.io.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;

/**
 *
 * @author NCRK (नवीन चौहान राजपूत खरदौनी)
 */
public class MainFrame extends javax.swing.JFrame implements KeyListener
{
private Property pro ;

    public MainFrame(Property pro) 
    {
        this.path = new  java.util.Vector<>();
        this.filename = new java.util.Vector<>();
        this.textArea = new java.util.Vector<>();
        this.scrollPane = new java.util.Vector<>();
        this.countTab = new java.util.Vector<>();
        this.countSpace = new java.util.Vector<>();
        this.pro = pro;
        initComponents();
        this.jToolBar1.setFloatable(false);
        this.jToolBar1.setRollover(true);
        this._changeEncoding(this.pro.encodingName);
        this.setBounds(this.pro.getRect());
        try
        {
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("images/title.jpg")));
        }
        catch(Exception e)
        {
            
        }
        setTitle("NCRK :: TextEditor v1.0.1");
        new TimeDateUpdationThread(this.jLabel1);
        _resigisterToolTipsText();
        if(this.pro.getFont_style()==1) 
        {
            jToggleButton1.setSelected(true);
        }
        else if(this.pro.getFont_style()==2)
        {
            jToggleButton2.setSelected(true);
        }
        this.i = -1;
       jTabbedPane2.setTabPlacement(JTabbedPane.TOP);
       {
        ++i;
        ++ni;
         _new();
       }
       //this.textArea.get(i).setText(System.getProperty("user.dir"));
       
        _addTrayIcon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem18 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();

        jMenuItem18.setText("null");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.gif"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.gif"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circle-x-2x.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-in-2x.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-out-2x.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cut.gif"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/copy.gif"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paste.gif"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.gif"))); // NOI18N
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton13);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bold.gif"))); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/italic.gif"))); // NOI18N
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/question.gif"))); // NOI18N
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        jScrollPane1.setViewportView(jToolBar1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel1.setText("Date and Time");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.gif"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jMenuItem1.setText(bundle.getString("NEW")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.gif"))); // NOI18N
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif"))); // NOI18N
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Save As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText(bundle.getString("SAVE ALL")); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText(bundle.getString("CLOSE")); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText(bundle.getString("CLOSE ALL")); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator3);
        jMenu1.add(jSeparator4);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText(bundle.getString("EXIT")); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("EDIT")); // NOI18N
        jMenu2.add(jSeparator5);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cut.gif"))); // NOI18N
        jMenuItem12.setText("Cut");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/copy.gif"))); // NOI18N
        jMenuItem13.setText("Copy");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paste.gif"))); // NOI18N
        jMenuItem14.setText("Paste");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);
        jMenu2.add(jSeparator6);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Select All");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenuItem15.setText("Text Color");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem26.setText("Background Color");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem26);
        jMenu3.add(jSeparator9);

        jMenuItem27.setText("Font");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem27);
        jMenu3.add(jSeparator7);

        jMenu11.setText("Look and Feel");

        jMenuItem31.setText("Nimbus");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem31);

        jMenu13.setText("Metal");

        jMenuItem34.setText("Default(Steel)");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem34);

        jMenuItem36.setText("Ocean");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem36);

        jMenu11.add(jMenu13);

        jMenuItem33.setText("Windows");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem33);

        jMenuItem32.setText("Windows Classics");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem32);

        jMenuItem30.setText("CDE/Motif");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem30);

        jMenu3.add(jMenu11);

        jMenu9.setText("ZOOM");

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_EQUALS, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-in-2x.png"))); // NOI18N
        jMenuItem17.setText("Zoom IN");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem17);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom-out-2x.png"))); // NOI18N
        jMenuItem19.setText("Zoom OUT");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenu3.add(jMenu9);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Encoding");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("US-ASCII");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("ISO-8859-1");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem4);
        jMenu7.add(jSeparator10);

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("UTF-8");
        jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem6);

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("UTF-16");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem5);
        jMenu7.add(jSeparator11);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("UTF-16BE");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("UTF-16LE");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Search");

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.gif"))); // NOI18N
        jMenuItem21.setText("Find");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem21);
        jMenu4.add(jSeparator8);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem23.setText("Replace");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Setting");

        jMenuItem35.setText("Reset to Default");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem35);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Help");

        jMenuItem9.setText("visit for Latest Version and Detail");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem24.setText("About us");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
         setI(getI() + 1);
        setNi(getNi() + 1);
        if(getI()<getMaxTab()) _new();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        setI(getI() + 1);
       if(getI()<getMaxTab()) {
           _open(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
         int si =getjTabbedPane2().getSelectedIndex();
         if(si==-1) {
             return;
         }
        _save(si);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int si = getjTabbedPane2().getSelectedIndex();
            if(si==-1) {
                return;
            }
        _close(si);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        _exit();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
         
        _zoomIn();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
         
        _zoomOut();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         
        setI(getI() + 1);
       if(getjTabbedPane2().getTabCount()<getMaxTab()) {
           _open(true);
      }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         
        setI(getI() + 1);
        setNi(getNi() + 1);
        if(getjTabbedPane2().getTabCount()<getMaxTab()) {
            _new();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         
        int si =getjTabbedPane2().getSelectedIndex();
        if(si==-1) return;
        _save(si);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         
        int si =getjTabbedPane2().getSelectedIndex();
        if(si==-1) return;
        _saveAs(si);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         int si = getjTabbedPane2().getSelectedIndex();
            if(si==-1) {
                return;
            }
        _close(si);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
         
        _paste();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
          
        _cut();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
         
        _copy();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    // Add in v1.0.1
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Search search = new Search(this,1);
        search.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
         
       javax.swing.JTextPane jp = new JTextPane();
       jp.setEnabled(true);
       jp.setVisible(true);
       jp.add(new JLabel("Close"));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        _zoomIn();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
        _zoomOut();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        boolean bold = getjToggleButton1().isSelected();
        boolean italic = getjToggleButton2().isSelected();
        if(!bold && !italic)
        {
            getPro().setFont_style(0); 
        }
        else if(bold && !italic)
        {
            getPro().setFont_style(1);
        }
        else
        {
            getjToggleButton2().setSelected(false);
            getPro().setFont_style(1);
        }
        for(int temp =0;temp<=getI();temp++) {
            textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        boolean bold = getjToggleButton1().isSelected();
        boolean italic = getjToggleButton2().isSelected();
        if(!bold && !italic)
        {
       
            getPro().setFont_style(0); 
        }
        else if(!bold && italic)
        {
            getPro().setFont_style(2);
        }
        else
        {
            getjToggleButton1().setSelected(false);
            getPro().setFont_style(2);
        }
        for(int temp =0;temp<=getI();temp++) {
            textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         
        _cut();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         
        _copy();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         
        _paste();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
         
        _selectAll();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
         
        _foregroundColorChooser();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
         
        _backgroundColorChooser();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    _aboutus();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        m32_Click(evt);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(this,"Are you sure to exit ?", "Exit", 1,QUESTION_MESSAGE);
        if(choice==0) 
        {
            pro.setRect(this.getBounds());
            getPro().writeProperties();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        _closeAll();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //UIManager.put("nimbusBase", new Color(255,100,100));
               //UIManager.put("control", new Color(255,0,100));
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Nimbus");
            getPro().theme = null;
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Windows");
            getPro().theme = null;
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("Windows Classic");
            getPro().theme = null;
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            getPro().setLook("CDE/Motif");
            getPro().theme = null;
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        Search search = new Search(this,1);
        search.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        Search search = new Search(this,0);
        search.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
         int option = JOptionPane.showConfirmDialog(this, "Are you sure to reset?\nNote::Save opened file before confirming to reset.");
         if(option==0)
         {
             dispose();
             String[] arg = new String[4];
             main(arg);
             
         }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        try {
            javax.swing.plaf.metal.MetalTheme theme=new javax.swing.plaf.metal.OceanTheme();
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(theme);
            try {
                UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            getPro().setLook("MetalLookAndFeel");
            getPro().theme = "Ocean";
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
       try {
           
           try {
               javax.swing.plaf.metal.MetalTheme theme=new javax.swing.plaf.metal.DefaultMetalTheme();
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(theme);
               UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
               javax.swing.SwingUtilities.updateComponentTreeUI(this);
           } catch (InstantiationException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
    getPro().setLook("MetalLookAndFeel");
    getPro().theme = "Steel";
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         catch (ClassNotFoundException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        this._aboutus();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      _saveAll();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
       _changeEncoding(this.jRadioButtonMenuItem2.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
       _changeEncoding(this.jRadioButtonMenuItem4.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
       _changeEncoding(this.jRadioButtonMenuItem6.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        _changeEncoding(this.jRadioButtonMenuItem5.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
       _changeEncoding(this.jRadioButtonMenuItem3.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        _changeEncoding(this.jRadioButtonMenuItem1.getText());
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

       try
       {
        Runtime.getRuntime().exec(System.getProperty("user.home") + "\\NCRK\\TextEditor\\v1.0.1\\visit.bat");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e, "Error",JOptionPane.INFORMATION_MESSAGE);
           System.out.println(e);
       }
    }//GEN-LAST:event_jMenuItem9ActionPerformed
void _new()
{
        this.textArea.add(getI(), new JTextArea("")) ;
        this.scrollPane.add(getI(), new JScrollPane());
        this.scrollPane.get(getI()).setViewportView(this.textArea.get(getI()));
        this.textArea.get(getI()).setTabSize(4);
        this.textArea.get(getI()).grabFocus();
        this.getjTabbedPane2().addTab("New "+getNi(),this.scrollPane.get(getI()));
        this.getjTabbedPane2().setToolTipTextAt(getI(), "New "+getNi()); // Add in v1.0.1
        this.textArea.get(getI()).setFont(new Font(getPro().getFont_name(), this.getPro().getFont_style(), getPro().getFont_size()));
        this.textArea.get(getI()).setBackground(getPro().getBgcolor());
        this.textArea.get(getI()).setForeground(getPro().getFgcolor());
        this.textArea.get(getI()).select(0, 0);
        this.textArea.get(getI()).addKeyListener(this);
        this.path.add("");
        this.filename.add("");
}
    
void _open(boolean _new)
	{
		//_close();
        if(_new)
        {
	setO(new FileDialog(this,"Open Files"));
        getO().setVisible(true);
        }
        if(getO().getFile()!=null||!_new)
        {
            if(_new)
            {
                path.add(getI(),getO().getDirectory()+getO().getFile());
                filename.add(getI(),getO().getFile());
            }
            
            try 
            ( //for byte oriented i/o
                    FileInputStream fin = new FileInputStream(path.get(getI()))) 
            {
                int length = fin.available();
                byte b[] = new byte[length];
                fin.read(b, 0, length);
                String str = new String(b, this.pro.encodingName);
                this.textArea.add(getI(), new JTextArea(""));
                this.textArea.get(getI()).setTabSize(2); this.textArea.get(getI()).grabFocus();
                this.textArea.get(getI()).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
                this.textArea.get(getI()).setBackground(getPro().getBgcolor());
                this.textArea.get(getI()).setForeground(getPro().getFgcolor());
                this.textArea.get(getI()).setText(str);
                this.textArea.get(getI()).setTabSize(4);
                this.scrollPane.add(getI(), new JScrollPane());
                this.scrollPane.get(getI()).setViewportView( this.textArea.get(getI()));
                this.getjTabbedPane2().addTab(getO().getFile(), this.scrollPane.get(getI()));
                this.scrollPane.get(getI()).setEnabled(true);
                this.scrollPane.get(getI()).setWheelScrollingEnabled(true);
                this.jTabbedPane2.setToolTipTextAt(getI(), this.filename.get(getI())); //Add in v1.0.1
                _setTitleAt(getI(),this.filename.get(getI())); //Add in v1.0.1
            }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to read the file\n "+path.get(getI())+e,"Error",0);
                this.textArea.get(getI()).setText("");
        }
        }
        else {
            setI(getI() - 1);
            }
	}

void _save(int i)
{
	if(path.get(i).equals(""))
        {
            setO(new FileDialog(this,"Save",1));
            getO().setVisible(true);   
        if( getO().getFile()!=null)
        {
                filename.setElementAt(getO().getFile(), i);
                path.setElementAt(getO().getDirectory()+filename.get(i), i);
        }
        else
        {
            return;
        }
	}    
        try (FileOutputStream fout = new FileOutputStream(path.get(i))) {
                byte b[] =  textArea.get(i).getText().getBytes(this.pro.encodingName);
                fout.write(b);
             getjTabbedPane2().setToolTipTextAt(i, filename.get(i)); //Add in v1.0.1
             _setTitleAt(i,this.filename.get(i)); //Add in v1.0.1
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to save the content into the file\n "+path.get(i)+e,"Error",0);
        }
       
        
}
        
    void _saveAs(int i)
{
    
	setO(new FileDialog(this,"Save As",1));
        getO().setVisible(true);
        if(getO().getFile()!=null)
        {
            filename.setElementAt(getO().getFile(), i);
            path.setElementAt(getO().getDirectory()+filename.get(i), i);
            try (FileOutputStream fout = new FileOutputStream(path.get(i))) {
            String txt = textArea.get(i).getText();
            byte[] b = txt.getBytes(this.pro.encodingName);
            fout.write(b,0,b.length);
            getjTabbedPane2().setTitleAt(i,filename.get(i));
        }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to save the content into the file\n "+path.get(i)+e,"Error",0);
        }
        }
               
}
    void _saveAll()
    {
        int count = this.textArea.size();
            for(int index =0;index<count;index++)
            {
                _save(index);
            }
    }

    void _close(int si)
	{
            
            if(this.path.get(i).equals("") && (!this.textArea.get(i).getText().equals("")))
            {
                int choice = javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to save the document before exiting ?", "confirmation", javax.swing.JOptionPane.YES_NO_CANCEL_OPTION , javax.swing.JOptionPane.QUESTION_MESSAGE);
                if(choice == 0)
                {
                    _save(si);
                }
                else if(choice == 2)
                {
                    return;
                }
            }
            else
            {
                try
                {
                    FileInputStream fin = new FileInputStream(this.path.get(si));
                    int length = fin.available();
                    byte[] b = new byte[length];
                    fin.read(b, 0, length);
                    fin.close();
                    String savedText = new java.lang.String(b,this.pro.encodingName);
                    String currentText = this.textArea.get(si).getText();
                    if(!savedText.equals(currentText))
                    {
                        int choice = javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to save the changes in document before exiting ?", "confirmation", javax.swing.JOptionPane.YES_NO_CANCEL_OPTION , javax.swing.JOptionPane.QUESTION_MESSAGE);
                        if(choice == 0)
                        {
                            _save(si);
                        }
                        else if(choice == 2)
                        {
                            return;
                        }
                    }
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
            this.setI(this.getI()-1);
            this.textArea.remove(si);
            this.scrollPane.remove(si);
            path.remove(si);
            filename.remove(si);
            getjTabbedPane2().remove(si);
	}
   
     void _closeAll()
    {
        int choice = JOptionPane.showConfirmDialog(this,"Do you want to exit without saving the documents/changes in those?");
	if(choice == 0)
        {
             System.exit(0);
        }
        else if(choice == 1)
        {
            int count = this.textArea.size();
            for(int index =0;index<count;index++)
            {
                _save(0);
                _close(0);
            }
        }
        else
        {
            return;
        }
    }
    void _cut()
    {
         int si =getjTabbedPane2().getSelectedIndex();
         textArea.get(si).cut();
    }
    void _copy()
    {
         int si =getjTabbedPane2().getSelectedIndex();
         textArea.get(si).copy();
    }
    void _paste()
    {
        int si =getjTabbedPane2().getSelectedIndex();
        textArea.get(si).paste();
    }
    void _selectAll()
    {
        int si =getjTabbedPane2().getSelectedIndex();
        textArea.get(si).selectAll();
    }
void _zoomIn()
{
	if(getPro().getFont_size()<72)
	{
            getPro().setFont_size(getPro().getFont_size() + 2);
            for(int temp=0;temp<=getI();temp++) {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
}
void _zoomOut()
{
	if(getPro().getFont_size()>12)
	{
            getPro().setFont_size(getPro().getFont_size() - 2);
            for(int temp=0;temp<=getI();temp++) {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
	}
        
}

void _foregroundColorChooser()
{
    new ForegroundColorChooser(this, this).setVisible(true);
}



void _backgroundColorChooser()
{
   new BackgroundColorChooser(this, this).setVisible(true);
}
void _aboutus()
{
    AboutUs aboutus = new AboutUs(this);
    
}

public void _print()
{
    PrintJob p = Toolkit.getDefaultToolkit().getPrintJob(this, getjTabbedPane2().getTitleAt(getjTabbedPane2().getSelectedIndex()), null, null);
        
       Graphics g1 =p.getGraphics();
       g1.dispose();
       p.end(); 
}

void _setFontStyle()
{
    boolean state = getjToggleButton2().isSelected();
        if(state)
        {
            for(int temp = 0;temp<=getI();temp++)
            {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
        else
        {
            for(int temp = 0;temp<=getI();temp++)
            {
                this.textArea.get(temp).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
            }
        }
}

/*
Add in v1.0.1 
*/
public void _changeEncoding(String encoding)
{
    this.jRadioButtonMenuItem1.setSelected(false);
    this.jRadioButtonMenuItem2.setSelected(false);
    this.jRadioButtonMenuItem3.setSelected(false);
    this.jRadioButtonMenuItem4.setSelected(false);
    this.jRadioButtonMenuItem5.setSelected(false);
    this.jRadioButtonMenuItem6.setSelected(false);
    switch(encoding)
    {
        case "UTF-16LE":this.jRadioButtonMenuItem1.setSelected(true);
                this.pro.encodingName= "UTF-16LE";
                break;
        case "US-ASCII":this.jRadioButtonMenuItem2.setSelected(true);
                this.pro.encodingName= "US-ASCII";
                break;
        case "UTF-16BE":this.jRadioButtonMenuItem3.setSelected(true);
                this.pro.encodingName= "UTF-16BE";
                break;
        case "ISO-8859-1":this.jRadioButtonMenuItem4.setSelected(true);
                this.pro.encodingName= "ISO-8859-1";
                break;
        case "UTF-16":this.jRadioButtonMenuItem5.setSelected(true);
                this.pro.encodingName= "UTF-16";
                break;
        case "UTF-8":this.jRadioButtonMenuItem6.setSelected(true);
                this.pro.encodingName= "UTF-8";
                break;
    }
}
/*
Add in v1.0.1 
*/
public void _resigisterToolTipsText()
{
    this.jButton1.setToolTipText("New Blank File");
    this.jButton2.setToolTipText("Open");
    this.jButton3.setToolTipText("Save");
    this.jButton4.setToolTipText("Close");
    this.jButton5.setToolTipText("Zoom IN");
    this.jButton6.setToolTipText("Zoom OUT");
    //this.jButton7.setToolTipText(" ");
    this.jButton8.setToolTipText("Cut");
    this.jButton9.setToolTipText("Copy");
    this.jButton10.setToolTipText("Paste");
    //this.jButton11.setToolTipText(" ");
    //this.jButton12.setToolTipText(" ");
    this.jButton13.setToolTipText("Find");
    //this.jButton14.setToolTipText(" ");
    //this.jButton15.setToolTipText(" ");
    //this.jButton16.setToolTipText("About Us");
    //this.jButton17.setToolTipText(" ");
    //this.jButton18.setToolTipText(" ");
    //this.jButton19.setToolTipText(" ");
    //this.jButton20.setToolTipText(" ");
    this.jToggleButton1.setToolTipText("Bold");
    this.jToggleButton2.setToolTipText("Italic");
}

/*
Add in v1.0.1
*/
public void _setTitleAt(int index , String text)
{
    if(text.length()>10)
    {
        this.jTabbedPane2.setTitleAt(index, text.substring(0,10)+"...");
    }
    else
    {
        this.jTabbedPane2.setTitleAt(index, text);
    }
}
       void m32_Click(ActionEvent e)
{
	//Font
	FontDialog f=new FontDialog( this);
	f.setVisible(true);
}
       
       public void _exit()
       {
           int choice = JOptionPane.showConfirmDialog(this,"Are you sure to exit ?", "Exit", 1,QUESTION_MESSAGE);
            if(choice==0) System.exit(0);
       }
       /*
       Add in v1.0.1
       */
       public void _addTrayIcon()
       {
           try
            {
                if(SystemTray.isSupported())
                {
                    SystemTray st = SystemTray.getSystemTray();
                    PopupMenu popupMenu = new PopupMenu("NCRK");
                    MenuItem mi1 = new java.awt.MenuItem("About us");
                    mi1.addActionListener(new ActionListener()
                    {
                        public void actionPerformed(ActionEvent evt )
                        {
                            _aboutus();
                        }
                    }
                    );
                    MenuItem mi2 = new MenuItem("Go To Web");
                    mi2.addActionListener(new ActionListener()
                    {
                        public void actionPerformed(ActionEvent evt)
                        {
                            try
                            {
                                 Runtime.getRuntime().exec(System.getProperty("user.home") + "\\NCRK\\TextEditor\\v1.0.1\\visit.bat");
                            }
                            catch(Exception e)
                            {
                                //JOptionPane.showMessageDialog(this, e, "Error",JOptionPane.INFORMATION_MESSAGE);
                                System.out.println(e);
                            }
                        }
                    }
                    );
                    MenuItem mi3 = new MenuItem("Exit");
                    mi3.addActionListener(new ActionListener()
                    {
                        public void actionPerformed(ActionEvent evt)
                        {
                            _exit();
                        }
                    }
                    );
                    popupMenu.add(mi1);
                    popupMenu.add(mi2);
                    popupMenu.add(mi3);
                    TrayIcon ti = new java.awt.TrayIcon(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("images/title1.jpg")), "NCRK :: TextEditor",popupMenu);
                    //ti.setImageAutoSize(true);
                 st.add(ti);
                }  
            }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e);
       }
       }
       
       
       /*
        Key Event handler Functions
       
       */
       public  void keyPressed(KeyEvent ke)
       {
           
       }
       public  void keyTyped(KeyEvent ke)
       {
           int keyCode = ke.getKeyCode();
           boolean space = false;
           boolean tab = false;
           if(keyCode == KeyEvent.VK_TAB) tab = true;
           else if(keyCode == KeyEvent.VK_SPACE) space = true;
           else return;
           int si = jTabbedPane2.getSelectedIndex();
           if(space)
           {
               this.countSpace.set(si, this.countSpace.get(si)+1);
           }
           else
           {
               this.countTab.set(si, this.countTab.get(si));
           }
           
       }
       public  void keyReleased(KeyEvent ke)
       {
           
       }
void db_click_open(String [] args)
{
   int j = 0;
    while(j<args.length)
    {
            j++;
            setI(getI() + 1);
            textArea.add(getI(), new JTextArea(""));
            textArea.get(getI()).setFont(new Font(getPro().getFont_name(), getPro().getFont_style(), getPro().getFont_size()));
	    path.add(getI(), args[j-1]);
            byte[] b;
            try { //for byte oriented i/o
                FileInputStream fin = new FileInputStream(path.get(getI()));
                int n = fin.available();
                b = new byte[n];
                fin.read(b,0,n);  
                fin.close();
                String str = new String(b);
                textArea.get(getI()).setText(str);
                textArea.get(getI()).setTabSize(2);
            
                scrollPane.add(getI(), new JScrollPane());
                scrollPane.get(getI()).setViewportView(textArea.get(getI()));
                getjTabbedPane2().addTab(getO().getFile(), scrollPane.get(getI()));
                scrollPane.get(getI()).setEnabled(true);
                scrollPane.get(getI()).setWheelScrollingEnabled(rootPaneCheckingEnabled);
                
        }catch(IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Sorry , we are not able to read the file\n "+path.get(getI())+e,"Error",0);
                textArea.get(getI()).setText("");
                setI(getI() - 1);
        }catch(Exception e)
        {
            setI(getI()-1);
        }
        
        //else i--;
    }
   
}

public javax.swing.JTabbedPane getjTabbedPane2()
    {
        return this.jTabbedPane2;
    }
 
    public static void main(String args[]) {
        Property pro = null;
        MainFrame f = null;
        if(args.length==0)
        {
             pro = Property.getProperty(false);
        }
        else
        {
             pro = Property.getProperty(true);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            if(pro.theme!=null)
            {
                 javax.swing.plaf.metal.MetalTheme theme = null;
                if(pro.theme.equals("Steel"))
                {
                    theme =new javax.swing.plaf.metal.DefaultMetalTheme();
                }
                else if(pro.theme.equals("Ocean"))
                {
                    theme=new javax.swing.plaf.metal.OceanTheme();
                }
                javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(theme);
            }
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (pro.getLook().equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>

        /* Create and display the form */
        Starting s = new Starting();
        s.setVisible(true);
        
        try
        {
            Thread.sleep(5000);
            
        }
        catch(InterruptedException e)
        {
            
        }
        s.dispose();
                f =  new MainFrame(pro);
                 f.setVisible(true);
//           System.out.println(args[0]);
          
          
         
        try
        {
        f.db_click_open(args);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }

private int MaxTab = 200;
private FileDialog o;
java.util.Vector<String> path;
java.util.Vector<String> filename;
java.util.Vector<Integer> countTab;
java.util.Vector<Integer> countSpace;
private int i=-1;
private int ni;//for indexing of New Tab (un-Saved)
java.util.Vector<JTextArea> textArea ;
java.util.Vector<JScrollPane> scrollPane ;
private String copiedText = "";
private GraphicsEnvironment g;
//private char[] ch;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pro
     */
    public Property getPro() {
        return pro;
    }

    /**
     * @param pro the pro to set
     */
    public void setPro(Property pro) {
        this.pro = pro;
    }

    /**
     * @return the MaxTab
     */
    public int getMaxTab() {
        return MaxTab;
    }

    /**
     * @param MaxTab the MaxTab to set
     */
    public void setMaxTab(int MaxTab) {
        this.MaxTab = MaxTab;
    }

    /**
     * @return the o
     */
    public FileDialog getO() {
        return o;
    }

    /**
     * @param o the o to set
     */
    public void setO(FileDialog o) {
        this.o = o;
    }

    /**
     * @return the i
     */
    public int getI() {
        return i;
    }

    /**
     * @param i the i to set
     */
    public void setI(int i) {
        this.i = i;
    }

    /**
     * @return the ni
     */
    public int getNi() {
        return ni;
    }

    /**
     * @param ni the ni to set
     */
    public void setNi(int ni) {
        this.ni = ni;
    }

    /**
     * @return the copiedText
     */
    public String getCopiedText() {
        return copiedText;
    }

    /**
     * @param copiedText the copiedText to set
     */
    public void setCopiedText(String copiedText) {
        this.copiedText = copiedText;
    }

    /**
     * @return the g
     */
    public GraphicsEnvironment getG() {
        return g;
    }

    /**
     * @param g the g to set
     */
    public void setG(GraphicsEnvironment g) {
        this.g = g;
    }


    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton10
     */
    public javax.swing.JButton getjButton10() {
        return jButton10;
    }

    /**
     * @param jButton10 the jButton10 to set
     */
    public void setjButton10(javax.swing.JButton jButton10) {
        this.jButton10 = jButton10;
    }


    /**
     * @return the jButton13
     */
    public javax.swing.JButton getjButton13() {
        return jButton13;
    }

    /**
     * @param jButton13 the jButton13 to set
     */
    public void setjButton13(javax.swing.JButton jButton13) {
        this.jButton13 = jButton13;
    }

    /**
     * @return the jButton16
     */
    public javax.swing.JButton getjButton16() {
        return jButton16;
    }

    /**
     * @param jButton16 the jButton16 to set
     */
    public void setjButton16(javax.swing.JButton jButton16) {
        this.jButton16 = jButton16;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.jButton3 = jButton3;
    }

    /**
     * @return the jButton4
     */
    public javax.swing.JButton getjButton4() {
        return jButton4;
    }

    /**
     * @param jButton4 the jButton4 to set
     */
    public void setjButton4(javax.swing.JButton jButton4) {
        this.jButton4 = jButton4;
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    /**
     * @return the jButton6
     */
    public javax.swing.JButton getjButton6() {
        return jButton6;
    }

    /**
     * @param jButton6 the jButton6 to set
     */
    public void setjButton6(javax.swing.JButton jButton6) {
        this.jButton6 = jButton6;
    }
    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return jButton8;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.jButton8 = jButton8;
    }

    /**
     * @return the jButton9
     */
    public javax.swing.JButton getjButton9() {
        return jButton9;
    }

    /**
     * @param jButton9 the jButton9 to set
     */
    public void setjButton9(javax.swing.JButton jButton9) {
        this.jButton9 = jButton9;
    }

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @param jMenu1 the jMenu1 to set
     */
    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }


    /**
     * @return the jMenu11
     */
    public javax.swing.JMenu getjMenu11() {
        return jMenu11;
    }

    /**
     * @param jMenu11 the jMenu11 to set
     */
    public void setjMenu11(javax.swing.JMenu jMenu11) {
        this.jMenu11 = jMenu11;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @param jMenu2 the jMenu2 to set
     */
    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     * @return the jMenu3
     */
    public javax.swing.JMenu getjMenu3() {
        return jMenu3;
    }

    /**
     * @param jMenu3 the jMenu3 to set
     */
    public void setjMenu3(javax.swing.JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    /**
     * @return the jMenu4
     */
    public javax.swing.JMenu getjMenu4() {
        return jMenu4;
    }

    /**
     * @param jMenu4 the jMenu4 to set
     */
    public void setjMenu4(javax.swing.JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    /**
     * @return the jMenu5
     */
    public javax.swing.JMenu getjMenu5() {
        return jMenu5;
    }

    /**
     * @param jMenu5 the jMenu5 to set
     */
    public void setjMenu5(javax.swing.JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }
    /**
     * @return the jMenu9
     */
    public javax.swing.JMenu getjMenu9() {
        return jMenu9;
    }

    /**
     * @param jMenu9 the jMenu9 to set
     */
    public void setjMenu9(javax.swing.JMenu jMenu9) {
        this.jMenu9 = jMenu9;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @param jMenuItem1 the jMenuItem1 to set
     */
    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

 

    /**
     * @return the jMenuItem12
     */
    public javax.swing.JMenuItem getjMenuItem12() {
        return jMenuItem12;
    }

    /**
     * @param jMenuItem12 the jMenuItem12 to set
     */
    public void setjMenuItem12(javax.swing.JMenuItem jMenuItem12) {
        this.jMenuItem12 = jMenuItem12;
    }

    /**
     * @return the jMenuItem13
     */
    public javax.swing.JMenuItem getjMenuItem13() {
        return jMenuItem13;
    }

    /**
     * @param jMenuItem13 the jMenuItem13 to set
     */
    public void setjMenuItem13(javax.swing.JMenuItem jMenuItem13) {
        this.jMenuItem13 = jMenuItem13;
    }

    /**
     * @return the jMenuItem14
     */
    public javax.swing.JMenuItem getjMenuItem14() {
        return jMenuItem14;
    }

    /**
     * @param jMenuItem14 the jMenuItem14 to set
     */
    public void setjMenuItem14(javax.swing.JMenuItem jMenuItem14) {
        this.jMenuItem14 = jMenuItem14;
    }

    /**
     * @return the jMenuItem15
     */
    public javax.swing.JMenuItem getjMenuItem15() {
        return jMenuItem15;
    }

    /**
     * @param jMenuItem15 the jMenuItem15 to set
     */
    public void setjMenuItem15(javax.swing.JMenuItem jMenuItem15) {
        this.jMenuItem15 = jMenuItem15;
    }

    /**
     * @return the jMenuItem16
     */
    public javax.swing.JMenuItem getjMenuItem16() {
        return jMenuItem16;
    }

    /**
     * @param jMenuItem16 the jMenuItem16 to set
     */
    public void setjMenuItem16(javax.swing.JMenuItem jMenuItem16) {
        this.jMenuItem16 = jMenuItem16;
    }

    /**
     * @return the jMenuItem17
     */
    public javax.swing.JMenuItem getjMenuItem17() {
        return jMenuItem17;
    }

    /**
     * @param jMenuItem17 the jMenuItem17 to set
     */
    public void setjMenuItem17(javax.swing.JMenuItem jMenuItem17) {
        this.jMenuItem17 = jMenuItem17;
    }

    /**
     * @return the jMenuItem18
     */
    public javax.swing.JMenuItem getjMenuItem18() {
        return jMenuItem18;
    }

    /**
     * @param jMenuItem18 the jMenuItem18 to set
     */
    public void setjMenuItem18(javax.swing.JMenuItem jMenuItem18) {
        this.jMenuItem18 = jMenuItem18;
    }

    /**
     * @return the jMenuItem19
     */
    public javax.swing.JMenuItem getjMenuItem19() {
        return jMenuItem19;
    }

    /**
     * @param jMenuItem19 the jMenuItem19 to set
     */
    public void setjMenuItem19(javax.swing.JMenuItem jMenuItem19) {
        this.jMenuItem19 = jMenuItem19;
    }

    /**
     * @return the jMenuItem2
     */
    public javax.swing.JMenuItem getjMenuItem2() {
        return jMenuItem2;
    }

    /**
     * @param jMenuItem2 the jMenuItem2 to set
     */
    public void setjMenuItem2(javax.swing.JMenuItem jMenuItem2) {
        this.jMenuItem2 = jMenuItem2;
    }

  
    /**
     * @return the jMenuItem21
     */
    public javax.swing.JMenuItem getjMenuItem21() {
        return jMenuItem21;
    }

    /**
     * @param jMenuItem21 the jMenuItem21 to set
     */
    public void setjMenuItem21(javax.swing.JMenuItem jMenuItem21) {
        this.jMenuItem21 = jMenuItem21;
    }

    /**
     * @return the jMenuItem23
     */
    public javax.swing.JMenuItem getjMenuItem23() {
        return jMenuItem23;
    }

    /**
     * @return the jMenuItem26
     */
    public javax.swing.JMenuItem getjMenuItem26() {
        return jMenuItem26;
    }

    /**
     * @param jMenuItem26 the jMenuItem26 to set
     */
    public void setjMenuItem26(javax.swing.JMenuItem jMenuItem26) {
        this.jMenuItem26 = jMenuItem26;
    }

    /**
     * @return the jMenuItem27
     */
    public javax.swing.JMenuItem getjMenuItem27() {
        return jMenuItem27;
    }

    /**
     * @param jMenuItem27 the jMenuItem27 to set
     */
    public void setjMenuItem27(javax.swing.JMenuItem jMenuItem27) {
        this.jMenuItem27 = jMenuItem27;
    }
    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return jMenuItem3;
    }

    /**
     * @param jMenuItem3 the jMenuItem3 to set
     */
    public void setjMenuItem3(javax.swing.JMenuItem jMenuItem3) {
        this.jMenuItem3 = jMenuItem3;
    }

    /**
     * @return the jMenuItem30
     */
    public javax.swing.JMenuItem getjMenuItem30() {
        return jMenuItem30;
    }

    /**
     * @param jMenuItem30 the jMenuItem30 to set
     */
    public void setjMenuItem30(javax.swing.JMenuItem jMenuItem30) {
        this.jMenuItem30 = jMenuItem30;
    }

    /**
     * @return the jMenuItem31
     */
    public javax.swing.JMenuItem getjMenuItem31() {
        return jMenuItem31;
    }

    /**
     * @param jMenuItem31 the jMenuItem31 to set
     */
    public void setjMenuItem31(javax.swing.JMenuItem jMenuItem31) {
        this.jMenuItem31 = jMenuItem31;
    }

    /**
     * @return the jMenuItem32
     */
    public javax.swing.JMenuItem getjMenuItem32() {
        return jMenuItem32;
    }

    /**
     * @param jMenuItem32 the jMenuItem32 to set
     */
    public void setjMenuItem32(javax.swing.JMenuItem jMenuItem32) {
        this.jMenuItem32 = jMenuItem32;
    }

    /**
     * @return the jMenuItem33
     */
    public javax.swing.JMenuItem getjMenuItem33() {
        return jMenuItem33;
    }

    /**
     * @param jMenuItem33 the jMenuItem33 to set
     */
    public void setjMenuItem33(javax.swing.JMenuItem jMenuItem33) {
        this.jMenuItem33 = jMenuItem33;
    }

    /**
     * @return the jMenuItem34
     */


    /**
     * @return the jMenuItem35
     */
    public javax.swing.JMenuItem getjMenuItem35() {
        return jMenuItem35;
    }

    /**
     * @param jMenuItem35 the jMenuItem35 to set
     */
    public void setjMenuItem35(javax.swing.JMenuItem jMenuItem35) {
        this.jMenuItem35 = jMenuItem35;
    }

    /**
     * @return the jMenuItem4
     */
    public javax.swing.JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    /**
     * @param jMenuItem4 the jMenuItem4 to set
     */
    public void setjMenuItem4(javax.swing.JMenuItem jMenuItem4) {
        this.jMenuItem4 = jMenuItem4;
    }

    /**
     * @return the jMenuItem5
     */
    public javax.swing.JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    /**
     * @param jMenuItem5 the jMenuItem5 to set
     */
    public void setjMenuItem5(javax.swing.JMenuItem jMenuItem5) {
        this.jMenuItem5 = jMenuItem5;
    }

    /**
     * @return the jMenuItem6
     */
    public javax.swing.JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    /**
     * @param jMenuItem6 the jMenuItem6 to set
     */
    public void setjMenuItem6(javax.swing.JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    /**
     * @return the jMenuItem7
     */
    public javax.swing.JMenuItem getjMenuItem7() {
        return jMenuItem7;
    }

    /**
     * @param jMenuItem7 the jMenuItem7 to set
     */
    public void setjMenuItem7(javax.swing.JMenuItem jMenuItem7) {
        this.jMenuItem7 = jMenuItem7;
    }

    /**
     * @return the jMenuItem8
     */
    public javax.swing.JMenuItem getjMenuItem8() {
        return jMenuItem8;
    }

    /**
     * @param jMenuItem8 the jMenuItem8 to set
     */
    public void setjMenuItem8(javax.swing.JMenuItem jMenuItem8) {
        this.jMenuItem8 = jMenuItem8;
    }

   
    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jSeparator1
     */
    public javax.swing.JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    /**
     * @param jSeparator1 the jSeparator1 to set
     */
    public void setjSeparator1(javax.swing.JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    /**
     * @return the jSeparator2
     */
    public javax.swing.JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    /**
     * @param jSeparator2 the jSeparator2 to set
     */
    public void setjSeparator2(javax.swing.JPopupMenu.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    /**
     * @return the jSeparator3
     */
    public javax.swing.JPopupMenu.Separator getjSeparator3() {
        return jSeparator3;
    }

    /**
     * @param jSeparator3 the jSeparator3 to set
     */
    public void setjSeparator3(javax.swing.JPopupMenu.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    /**
     * @return the jSeparator4
     */
    public javax.swing.JPopupMenu.Separator getjSeparator4() {
        return jSeparator4;
    }

    /**
     * @param jSeparator4 the jSeparator4 to set
     */
    public void setjSeparator4(javax.swing.JPopupMenu.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    /**
     * @return the jSeparator5
     */
    public javax.swing.JPopupMenu.Separator getjSeparator5() {
        return jSeparator5;
    }

    /**
     * @param jSeparator5 the jSeparator5 to set
     */
    public void setjSeparator5(javax.swing.JPopupMenu.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    /**
     * @return the jSeparator6
     */
    public javax.swing.JPopupMenu.Separator getjSeparator6() {
        return jSeparator6;
    }

    /**
     * @param jSeparator6 the jSeparator6 to set
     */
    public void setjSeparator6(javax.swing.JPopupMenu.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    /**
     * @param jTabbedPane2 the jTabbedPane2 to set
     */
    public void setjTabbedPane2(javax.swing.JTabbedPane jTabbedPane2) {
        this.jTabbedPane2 = jTabbedPane2;
    }

    /**
     * @return the jToggleButton1
     */
    public javax.swing.JToggleButton getjToggleButton1() {
        return jToggleButton1;
    }

    /**
     * @param jToggleButton1 the jToggleButton1 to set
     */
    public void setjToggleButton1(javax.swing.JToggleButton jToggleButton1) {
        this.jToggleButton1 = jToggleButton1;
    }

    /**
     * @return the jToggleButton2
     */
    public javax.swing.JToggleButton getjToggleButton2() {
        return jToggleButton2;
    }

    /**
     * @param jToggleButton2 the jToggleButton2 to set
     */
    public void setjToggleButton2(javax.swing.JToggleButton jToggleButton2) {
        this.jToggleButton2 = jToggleButton2;
    }

    /**
     * @return the jToolBar1
     */
    public javax.swing.JToolBar getjToolBar1() {
        return jToolBar1;
    }

    /**
     * @param jToolBar1 the jToolBar1 to set
     */
    public void setjToolBar1(javax.swing.JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }
}
